apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapp
  name: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
      version: 0.0.1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp
        version: 0.0.1
    spec:
      containers:
      - image: simpleapp:0.0.1
        name: simpleapp
        imagePullPolicy: Never
        ports:
          - containerPort: 80
        env:
          - name: BUILD_VERSION
            value: 0.0.1
          - name: BUILD_TIME
            value: 2021-09-25_06:32:44
          - name: BUILD_IMAGE
            value: simpleapp:0.0.1
        resources:
            requests:
              cpu: "15m"
              memory: "15Mi"
            limits:
              cpu: "50m"
              memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /status/healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /status/readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3