apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.APP_NAME}}
  name: {{.APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.APP_NAME}}
      version: {{.VERSION}}
  template:
    metadata:
      labels:
        app: {{.APP_NAME}}
        version: {{.VERSION}}
    spec:
      containers:
      - image: {{.CONTAINER_REPOSITORY}}/{{.IMAGE_NAME}}
        name: {{.APP_NAME}}
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: BUILD_VERSION
            value: {{.VERSION}}
          - name: BUILD_TIME
            value: {{.BUILD_TIME}}
          - name: BUILD_IMAGE
            value: {{.IMAGE_NAME}}
        resources:
            requests:
              cpu: "15m"
              memory: "15Mi"
            limits:
              cpu: "50m"
              memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /status/healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /status/readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3