apiVersion: v1
kind: Service
metadata:
  name: {{.APP_NAME}}-nodeport-service
  labels:
    app: {{.APP_NAME}}
    version: {{.VERSION}}
spec:
  type: NodePort
  selector:
    app: {{.APP_NAME}}
    version: {{.VERSION}}
  ports:
  - port: 80
    targetPort: 80
